online_store/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from store.forms import AuthenticationNewForm

urlpatterns = [
    path('admin/', admin.site.urls),
path('', include('django.contrib.auth.urls')),
    path('', include('store.urls')),
    path("login/", views.LoginView.as_view(form_class=AuthenticationNewForm), name="login"),
    path('', include('django.contrib.auth.urls')),


]

store/urls.py
from django.urls import path
from store import views
from store.views import remove_from_cart

urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name='home_page'),
    path('', views.HomeTemplateView.as_view(), name='base'),
    path('login', views.HomeTemplateView.as_view(), name='login'),
    path('create_user/', views.UserCreateView.as_view(), name='create-user'),
    path('product_list/', views.ProductListView.as_view(), name='product_list'),
    path('category/<int:pk>', views.CategoryProductsView.as_view(), name='category_list'),
    path('product_detail/<int:product_id>/', views.product_details, name='product-detail'),
    path('create_product/', views.ProductCreateView.as_view(), name="create-product"),
    path('modify_product/<int:pk>/', views.ProductUpdateView.as_view(), name="modify-product"),
    path('delete_product/<int:product_id>/', views.delete_product, name="delete-product"),
    path('open-cart/', views.open_cart_view, name='open_cart'),
    path('add-product-to-cart/', views.add_product_to_cart, name='add_product_to_cart'),
    path('remove/<int:product_id>/', views.remove_from_cart, name='remove-product-from-cart'),
    path('remove/<int:product_id>/', remove_from_cart, name='remove-product-from-cart'),
    path('contact/', views.contact, name='contact'),
    path('contact-confirm/', views.contact_confirm_view, name='contact_confirm'),
    path('search/', views.search_results, name='search_results'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('proceed_to_payment/', views.proceed_to_payment, name='proceed_to_payment'),
    path('add-category/', views.CategoryCreateView.as_view(), name="add_category"),
    path('produse-reduse/', views.reduced_products, name="reduced-products"),
    path('comenzile_mele/', views.IstoricCumparaturiView.as_view(), name='comenzile-mele'),
    path('multumim/', views.SuccesPaymentView.as_view(), name='ms'),
    path('mail_contact/', views.SuccesMailView.as_view(), name='mail-contact'),

    path('send_email/', views.send_email, name='send-email'),

]

store/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=250)
    active = models.BooleanField(default=True)
    parent_category = models.ForeignKey('Category', on_delete=models.CASCADE, blank=True, null=True)

    def subcategories(self):
        return Category.objects.filter(parent_category=self)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField()
    descriptions = models.TextField()
    active = models.BooleanField(default=True)
    image = models.ImageField(upload_to='static/product_images/', null=True, blank=True)
    discount_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    discount_price_valid_until = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.name


# class History(models.Model):
#     text = models.TextField(max_length=400)
#     created_at = models.DateTimeField(auto_now_add=True)
#
#     def __str__(self):
#         return self.text


class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)


class UserProductPurchased(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.product}"

    class Meta:
        unique_together = ['user', 'product']


class Cart(models.Model):
    STATUS = (
        ('open', 'Open'),
        ('closed', 'Closed'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=50, choices=STATUS, default='open')
    products = models.ManyToManyField(Product, blank=True)

    def __str__(self):
        return f'{self.status} cart of {self.user}'


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.quantity} X {self.product} in {self.cart}'

templates/divers/cart.html
{% extends 'base.html' %} {% block content %}

<div class="shoppingCart">
  <h2>My Cart</h2>

  <div class="heading">
    <div class="p_name"><h4>Product's Name</h4></div>
    <div class="name"><h4>Quantity</h4></div>
    <div class="name"><h4>Unit Price</h4></div>
    <div class="name"><h4>Prize</h4></div>
  </div>

  <div class="itemContainer">

    {% for item in items %}
    <div class="item">
      <div class="iteminfo">
        <div class="p_img">
          <img src="{{item.product.picture.url}}" alt="" />
        </div>
        <p>{{item.product.name}}</p>
      </div>

      <div class="name"><p>{{item.quantity}}</p></div>
      <div class="name"><p>${{item.product.price}}</p></div>
      <div class="name"><p>${{item.price}}</p></div>
    </div>

    {% endfor %}
  </div>

  <div class="pay-section">
    <h3>Grand-Total: ${{cart.total_price}}</h3>
    <button onclick = "makePayment()" >Pay</button>
  </div>
</div>

<script src="https://checkout.flutterwave.com/v3.js"></script>
<script>

let cart_total = "{{cart.total_price}}"
let cart_id = "{{cart.id}}"


  function makePayment() {
    FlutterwaveCheckout({
      public_key: "FLWPUBK_TEST-PUBLIC KEY",
      tx_ref: "titanic-48981487343MDI0NzMx",
      amount: cart_total,
      currency: "USD",
      payment_options: "card, mobilemoneyghana, ussd",
      redirect_url: "http://127.0.0.1:8000/confirm_payment/"+cart_id,
      meta: {
        consumer_id: 23,
        consumer_mac: "92a3-912ba-1192a",
      },
      customer: {
        email: "rose@unsinkableship.com",
        phone_number: "08102909304",
        name: "{{request.user.username}}",
      },
      customizations: {
        title: "My Shop",
        description: "Buy with ease",
        logo: "https://www.logolynx.com/images/logolynx/22/2239ca38f5505fbfce7e55bbc0604386.jpeg",
      },
    });
  }

</script>

{% endblock content %}

templates/divers/item_detail.html
{#{% if request.user.is_authenticated %}#}
{#    {% if item in request.user.favorite_set.all %}#}
        <form action="{% url 'remove_favorite' product_id= product_id  %}" method="post">
            {% csrf_token %}
            <button type="submit">Remove from Favorites</button>
        </form>
{#    {% else %}#}
        <form action="{% url 'add_favorite' product_id= product_id %}" method="post">
            {% csrf_token %}
            <button type="submit">Add to Favorites</button>
        </form>
{#    {% endif %}#}
{#{% else %}#}
    <p>Login to add this item to your favorites.</p>
{#{% endif %}#}

templates/divers/prod.html
{#{% extends 'base.html' %}#}
{##}
{#{% block title %} List of trainers {% endblock %}#}
{##}
{#{% block content %}#}
{##}
{##}
{#    <div class="container-fluid">#}
{#        <div class="mb-3 text-primary text-center ">#}
{#        </div>#}
{#        <div class="row">#}
{#            {% for products in products %}#}
{#                <div class="col-md-4 mb-3">#}
{#                    <div class="card">#}
{#                                    <h5 class="card-title">#}
{##}
{##}
{##}
{#                        <img src="{{ products.logo }}" class="card-img-top" alt="...">#}
{#                        <div class="card-body">#}
{#                            <h5 class="card-title">{{ products.name }}</h5>#}
{#                            <p class="card-text">{{ products.price }}</p>#}
{#                            <a href="#" class="btn btn-primary">adauga in cos</a>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#                </div>#}
{##}
{##}
{#            {% endfor %}#}
{#    </ul>#}
{##}
{#{% endblock %}#}


{% extends 'base.html' %}

{% block title %} List of trainers {% endblock %}

{% block content %}


<div class="container-fluid">
    <div class="row">
        {#            <div class="col-md-2">#}
        {#                <div class="card">#}
        {#                    <div class="card-header">#}
        {#                        <h3 class="text-center">Filters</h3>#}
        {#                    </div>#}
        {#                    <form method="GET">#}
        {#                        <div class="card-body">#}
        {#                            {{ form_filters.as_p }}#}
        {#                        </div>#}
        {#                        <div class="card-footer text-center">#}
        {#                            <button type="submit" class="btn btn-outline-success">Search</button>#}
        {#                            <a href="{% url 'list-of-trainers' %}" class="btn btn-outline-danger">Reset</a>#}
        {#                        </div>#}
        {#                    </form>#}
        {#                </div>#}
        {#            </div>#}


        <div class="col-md-8">
            <div class="row">
                {% for products in products %}


                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="..." alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of
                            the card's content.</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>


                <div class="col-md-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">
                                Name: {{ trainer.first_name }} {{ trainer.last_name }}</h5>
                            <p class="card-text">Course: {{ trainer.course }}</p>
                            <p class="card-text">Email: {{ trainer.email }}</p>
                            <p class="card-text">Department:{{ trainer.departament }}</p>
                            <div class="dropdown">
                                <button class="btn btn-outline-success dropdown-toggle" type="button"
                                        data-bs-toggle="dropdown" aria-expanded="false">
                                    More actions
                                </button>
                                <ul class="dropdown-menu">

                                    <li><a class="dropdown-item"
                                           href="{% url 'update-trainer' trainer.id %}">Update</a>
                                    </li>

                                    <li><a class="dropdown-item"
                                           href="{% url 'delete-trainer' trainer.id %}">Delete</a>
                                    </li>
                                    {% endif %}

                                    <li><a class="dropdown-item"
                                           href="{% url 'details-trainer' trainer.id %}">View</a>
                                    </li>

                                </ul>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/divers/product_buy.html
{% extends 'base.html' %}

{% block title %}Buy Product{% endblock %}

{% block content %}
    <div class="container-fluid my-container" style="margin-bottom: 50px;">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-body">
                        <h2 class="card-title">Esti sigur ?</h2>
                        <p class="card-text">Vrei sa adaugi {{ product.name }} in cos?</p>
                        <h5 class="card-title mb-4" style="font-size: 24px;">Pretul este de {{ product.price }} lei </h5>
                        <form action="{% url 'process_payment' product.id %}" method="post">
                            {% csrf_token %}
                            <button class="btn btn-primary" type="submit">Adauga</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/divers/product_list_pk.html
{% extends 'base.html' %}
{% load static %}

{% block title %} List of products {% endblock %}

{% block content %}


    <div class="container-fluid">
        <div class="row">

            <div class="col-md-3">
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Filtrare</h3>
                    </div>
                    <form method="GET">
                        <div class="card-body">
                            {{ form_filters.as_p }}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-outline-success">Search</button>
                            <a href="{% url 'product_list' %}" class="btn btn-outline-danger">Reset</a>
                        </div>
                    </form>
                </div>
            </div>
            {#        <div class="mb-3 text-primary text-center ">#}
            {#            <img src="{% static 'product_images/logo.jpg' %}" width="30%" alt="Online Store">#}
            {#        </div>#}
            <div class="col-md-8">
                <div class="row">
                    {% for products in products %}
                        <div class="col-md-4 mb-4">
                            <div class="card" style="width: 18rem;">
                                {% if products.image %}
                                    <img src="{{ products.image.url }}" class="card-img-top" alt="{{ products.name }}">
                                {% else %}
                                    <img class='card-img-top' src="{% static 'product_images/no_image.jpeg' %}"
                                         alt='Image Not Available'
                                         style='width: 200px;'>
                                {% endif %}
                                <div class="card-body">
                                    <h5 class="card-title">{{ products.name }}</h5>
{#                                    <p class="card-text">{{ products.descriptions }}</p>#}
{#                                    <h5 class="card-title">{{ products.price }}</h5>#}
{#                                    <h6 class="card-title">{{ products.quantity }} produse disponibile</h6>#}
{#                                    <a href="#" class="btn btn-primary">#}
{#                                        <svg xmlns="http://www.w3.org/2000/svg" height="2em" viewBox="0 0 576 512"><!--! Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><style>svg{fill:#2a67cf}</style><path d="M0 24C0 10.7 10.7 0 24 0H69.5c22 0 41.5 12.8 50.6 32h411c26.3 0 45.5 25 38.6 50.4l-41 152.3c-8.5 31.4-37 53.3-69.5 53.3H170.7l5.4 28.5c2.2 11.3 12.1 19.5 23.6 19.5H488c13.3 0 24 10.7 24 24s-10.7 24-24 24H199.7c-34.6 0-64.3-24.6-70.7-58.5L77.4 54.5c-.7-3.8-4-6.5-7.9-6.5H24C10.7 48 0 37.3 0 24zM128 464a48 48 0 1 1 96 0 48 48 0 1 1 -96 0zm336-48a48 48 0 1 1 0 96 48 48 0 1 1 0-96z"/></svg>#}
{#                                    </a>#}
{#                                    <span class="spanen">&nbsp;</span>        <span class="spanen">&nbsp;</span>#}
{#                                    <a href="#" class="btn btn-primary">#}
{#                                        <svg xmlns="http://www.w3.org/2000/svg" height="2em" viewBox="0 0 512 512"><!--! Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><style>svg{fill:#ffffff}</style><path d="M47.6 300.4L228.3 469.1c7.5 7 17.4 10.9 27.7 10.9s20.2-3.9 27.7-10.9L464.4 300.4c30.4-28.3 47.6-68 47.6-109.5v-5.8c0-69.9-50.5-129.5-119.4-141C347 36.5 300.6 51.4 268 84L256 96 244 84c-32.6-32.6-79-47.5-124.6-39.9C50.5 55.6 0 115.2 0 185.1v5.8c0 41.5 17.2 81.2 47.6 109.5z"/></svg>#}
{#                                    </a>#}
{#                                    <span class="spanen">&nbsp;</span>     <span class="spanen">&nbsp;</span>#}
{#                                    <a href="#" class="btn btn-primary">#}
{#                                        <svg xmlns="http://www.w3.org/2000/svg" height="2em" viewBox="0 0 576 512"><!--! Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M288 32c-80.8 0-145.5 36.8-192.6 80.6C48.6 156 17.3 208 2.5 243.7c-3.3 7.9-3.3 16.7 0 24.6C17.3 304 48.6 356 95.4 399.4C142.5 443.2 207.2 480 288 480s145.5-36.8 192.6-80.6c46.8-43.5 78.1-95.4 93-131.1c3.3-7.9 3.3-16.7 0-24.6c-14.9-35.7-46.2-87.7-93-131.1C433.5 68.8 368.8 32 288 32zM144 256a144 144 0 1 1 288 0 144 144 0 1 1 -288 0zm144-64c0 35.3-28.7 64-64 64c-7.1 0-13.9-1.2-20.3-3.3c-5.5-1.8-11.9 1.6-11.7 7.4c.3 6.9 1.3 13.8 3.2 20.7c13.7 51.2 66.4 81.6 117.6 67.9s81.6-66.4 67.9-117.6c-11.1-41.5-47.8-69.4-88.6-71.1c-5.8-.2-9.2 6.1-7.4 11.7c2.1 6.4 3.3 13.2 3.3 20.3z"/></svg>#}
{#                                    </a>#}

                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/divers/purchased_product.html
{% extends 'base.html' %}

{% block title %}Purchased Tutorial - {{ product.name }}{% endblock %}

{% block content %}
    <div class="container-fluid my-container" style="margin-bottom: 50px;">
        <div class="row">
            <div class="col-md-8 offset-md-2 my-content">
                <div class="card">
                    <div class="card-body text-center">
                        <h2 class="card-title">Purchased product - {{ product.name }}</h2>
                        <br>
                        <div class="d-flex justify-content-between mb-3">
                            <h6 class="text-right">Category: <br>{{ product.category }}</h6>
{#                            <h6 class="text-right">Trainer name: <br>{{ tutorial.tutor.first_name }} {{ tutorial.tutor.last_name }}</h6>#}
                        </div>
                        <br>
{#                        <div>#}
{#                            <iframe width="100%" height="500"#}
{#                                    src="{{ tutorial.link_url }}" title="YouTube video player" frameborder="0"#}
{#                                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"#}
{#                                    allowfullscreen></iframe>#}
{#                        </div>#}
                        <br>
                        <div class="text-left">
{#                            <h6>Details long: <br>{{ tutorial.description_long }}</h6>#}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/divers/purchased_successful.html
{% extends 'base.html' %}

{% block title %}Purchased Successful{% endblock %}

{% block content %}
    <div class="container-fluid my-container" style="margin-bottom: 50px;">
        <div class="row">
            <div class="col-md-8 offset-md-2 my-content">
                <div class="card">
                    <div class="card-body text-center">
                        <h2 class="card-title">Purchased Successful</h2>
                        <p>Your purchase was successful!</p>
                        <a href="{% url 'product-detail' product.id %}" class="btn btn-primary">Vezi cos</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}