online_store/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from store.forms import AuthenticationNewForm

urlpatterns = [
    path('admin/', admin.site.urls),
path('', include('django.contrib.auth.urls')),
    path('', include('store.urls')),
    path("login/", views.LoginView.as_view(form_class=AuthenticationNewForm), name="login"),
    path('', include('django.contrib.auth.urls')),


]

store/urls.py
from django.urls import path
from store import views
from store.views import remove_from_cart

urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name='home_page'),
    path('', views.HomeTemplateView.as_view(), name='base'),
    path('login', views.HomeTemplateView.as_view(), name='login'),
    path('create_user/', views.UserCreateView.as_view(), name='create-user'),
    path('product_list/', views.ProductListView.as_view(), name='product_list'),
    path('category/<int:pk>', views.CategoryProductsView.as_view(), name='category_list'),
    path('product_detail/<int:product_id>/', views.product_details, name='product-detail'),
    path('create_product/', views.ProductCreateView.as_view(), name="create-product"),
    path('modify_product/<int:pk>/', views.ProductUpdateView.as_view(), name="modify-product"),
    path('delete_product/<int:product_id>/', views.delete_product, name="delete-product"),
    path('open-cart/', views.open_cart_view, name='open_cart'),
    path('add-product-to-cart/', views.add_product_to_cart, name='add_product_to_cart'),
    path('remove/<int:product_id>/', views.remove_from_cart, name='remove-product-from-cart'),
    path('remove/<int:product_id>/', remove_from_cart, name='remove-product-from-cart'),
    path('contact/', views.contact, name='contact'),
    path('contact-confirm/', views.contact_confirm_view, name='contact_confirm'),
    path('search/', views.search_results, name='search_results'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('proceed_to_payment/', views.proceed_to_payment, name='proceed_to_payment'),
    path('add-category/', views.CategoryCreateView.as_view(), name="add_category"),
    path('produse-reduse/', views.reduced_products, name="reduced-products"),
    path('comenzile_mele/', views.IstoricCumparaturiView.as_view(), name='comenzile-mele'),
    path('multumim/', views.SuccesPaymentView.as_view(), name='ms'),
    path('mail_contact/', views.SuccesMailView.as_view(), name='mail-contact'),

    path('send_email/', views.send_email, name='send-email'),

]

store/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from django.core.validators import EmailValidator
from django.forms import TextInput

from store.models import Product, Category


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username'
                  ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['first_name'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Please enter your first name'})
        self.fields['last_name'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Please enter your last name'})
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Please enter your email address'})
        self.fields['username'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Please enter your username'})
        self.fields['password1'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Please enter your password'})
        self.fields['password2'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Please re-enter your password'})


class AuthenticationNewForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Please enter your username'})
        self.fields['password'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Please enter your password'})


class SpecialPriceForm(forms.Form):
    special_price = forms.DecimalField(label='Special Price', max_digits=8, decimal_places=2)


class CategoryForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username']


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.CharField(validators=[EmailValidator()])
    phone = forms.CharField(max_length=15)
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

        widgets = {
            'name': TextInput(attrs={'placeholder': 'Please enter product name', 'class': 'form-control'}),
            'discount_price_valid_until': TextInput(
                attrs={'placeholder': 'Year  Month  Day ', 'class': 'form-control'}),
        }

        def clean(self):
            cleaned_data = self.cleaned_data
            check_emails = Product.objects.filter(email=cleaned_data['email'])
            if check_emails:
                msg = 'Aceasta adresa de mail exista deja in db'
                self._errors['email'] = self.error_class([msg])

            if 'image' in cleaned_data and not cleaned_data['image']:
                self.add_error('image', 'Please upload an image for the product.')

            get_start_date = cleaned_data['start_date']
            get_end_date = cleaned_data['end_date']
            if get_start_date > get_end_date:
                msg = 'Start date-ul introdus este mai mare decat end date'
                self._errors['start_date'] = self.error_class([msg])

            return cleaned_data


class ProductUpdateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'


class CheckoutForm(forms.Form):
    shipping_address = forms.CharField(label='Adresa de livrare', widget=forms.Textarea(attrs={'rows': 3}))
    billing_address = forms.CharField(label='Adresa de facturare', widget=forms.Textarea(attrs={'rows': 3}))
    # card_number = forms.CharField(label='Numar card', max_length=16)
    # card_expiry = forms.CharField(label='Data expirate card', max_length=5, help_text='MM/YY')
    # card_cvc = forms.CharField(label='Card CVC', max_length=3)


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'active', 'parent_category']

templates/add_special_price.html
{% extends 'base.html' %}

{% block title %} Special Price {% endblock %}

{% block content %}
    <h1>Add Special Price for {{ product.name }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/cart_style.css' %}">


</head>
<body>
{% include 'navbar.html' %}


{% block content %}{% endblock %}


<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity=
        "sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity=
        "sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>


<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="container text-center bg-container">
        <div class="container text-center">
            <div class="row row-cols-1">
            </div>
            <div class="col-md-12">
                <img class="bg-img" src="/static/product_images/logo.jpg" alt="..." style="width: 50%;">
            </div>
        </div>
    </div>
    <div class="col-md-12 d-flex align-items-center">
        <a href="#" class=" lh-1">
            <svg class="bi" width="30" height="24">
            </svg>
        </a>
        <span class="mb-3 mb-md-0 text-body-secondary">&copy; 2023 Online Store</span>
    </div>
</footer>
</div>


</body>
</html>

templates/category_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ category.name }} Products
{% endblock %}
{% block content %}
    <div class="container text-center">
        <h1>{{ category.name }}</h1>

        <div class="row">
            <div class="col-md-10 offset-md-1">
                <div class="row">
                    {% for product in products %}
                        <div class="col-md-3 mb-3 d-flex">
                            <div class="product-card card flex-fill">
                                <div class="product-image">
                                    {% if product.image %}
                                        <img src="{{ product.image.url }}" class="img-fluid" alt="{{ product.name }}">
                                    {% else %}
                                        <img src="{% static 'product_images/no_image.jpeg' %}" class="img-fluid"
                                             alt="Image Not Available">
                                    {% endif %}
                                </div>
                                <div class="product-details">
                                    <h5 class="card-title">{{ product.name }}</h5>
                                    <p class="card-text">{{ product.price }} Lei</p>
                                    <p class="card-text">{{ product.quantity }} produse disponibile</p>
                                    <div class="d-flex justify-content-between">
                                        <form action="{% url 'add_product_to_cart' %}" method="post">
                                            {% csrf_token %}
                                            <input type="hidden" name="product_id" value="{{ product.id }}">

                                            <button type="submit" class="btn btn-primary">
                                                <svg xmlns="http://www.w3.org/2000/svg" height="1em"
                                                     viewBox="0 0 576 512">
                                                    <path d="M528.12 301.319l47.273-208C578.806 78.301 567.391 64 551.99 64H159.208l-9.166-44.81C147.758 8.021 137.93 0 126.529 0H24C10.745 0 0 10.745 0 24v16c0 13.255 10.745 24 24 24h69.883l70.248 343.435C147.325 417.1 136 435.222 136 456c0 30.928 25.072 56 56 56s56-25.072 56-56c0-15.674-6.447-29.835-16.824-40h209.647C430.447 426.165 424 440.326 424 456c0 30.928 25.072 56 56 56s56-25.072 56-56c0-22.172-12.888-41.332-31.579-50.405l5.517-24.276c3.413-15.018-8.002-29.319-23.403-29.319H218.117l-6.545-32h293.145c11.206 0 20.92-7.754 23.403-18.681z"></path>
                                                </svg>
                                            </button>
                                        </form>
                                        <a href="{% url 'product-detail' product.id %}" class="btn btn-primary">
                                            <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 576 512">
                                                <path d="M288 32c-80.8 0-145.5 36.8-192.6 80.6C48.6 156 17.3 208 2.5 243.7c-3.3 7.9-3.3 16.7 0 24.6C17.3 304 48.6 356 95.4 399.4C142.5 443.2 207.2 480 288 480s145.5-36.8 192.6-80.6c46.8-43.5 78.1-95.4 93-131.1c3.3-7.9 3.3-16.7 0-24.6c-14.9-35.7-46.2-87.7-93-131.1C433.5 68.8 368.8 32 288 32zM144 256a144 144 0 1 1 288 0 144 144 0 1 1 -288 0zm144-64c0 35.3-28.7 64-64 64c-7.1 0-13.9-1.2-20.3-3.3c-5.5-1.8-11.9 1.6-11.7 7.4c.3 6.9 1.3 13.8 3.2 20.7c13.7 51.2 66.4 81.6 117.6 67.9s81.6-66.4 67.9-117.6c-11.1-41.5-47.8-69.4-88.6-71.1c-5.8-.2-9.2 6.1-7.4 11.7c2.1 6.4 3.3 13.2 3.3 20.3z"></path>
                                            </svg>
                                        </a>
                                        {% if user.is_staff %}
                                            <a href="{% url 'modify-product' product.id %}" class="btn btn-primary">
                                                <svg xmlns="http://www.w3.org/2000/svg" height="1em"
                                                     viewBox="0 0 512 512">
                                                    <path d="M471.6 21.7c-21.9-21.9-57.3-21.9-79.2 0L362.3 51.7l97.9 97.9 30.1-30.1c21.9-21.9 21.9-57.3 0-79.2L471.6 21.7zm-299.2 220c-6.1 6.1-10.8 13.6-13.5 21.9l-29.6 88.8c-2.9 8.6-.6 18.1 5.8 24.6s15.9 8.7 24.6 5.8l88.8-29.6c8.2-2.7 15.7-7.4 21.9-13.5L437.7 172.3 339.7 74.3 172.4 241.7zM96 64C43 64 0 107 0 160V416c0 53 43 96 96 96H352c53 0 96-43 96-96V320c0-17.7-14.3-32-32-32s-32 14.3-32 32v96c0 17.7-14.3 32-32 32H96c-17.7 0-32-14.3-32-32V160c0-17.7 14.3-32 32-32h96c17.7 0 32-14.3 32-32s-14.3-32-32-32H96z"></path>
                                                </svg>
                                            </a>
                                            <a href="{% url 'delete-product' product.id %}" class="btn btn-primary">
                                                <svg xmlns="http://www.w3.org/2000/svg" height="1em"
                                                     viewBox="0 0 448 512">
                                                    <path d="M135.2 17.7L128 32H32C14.3 32 0 46.3 0 64S14.3 96 32 96H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H320l-7.2-14.3C307.4 6.8 296.3 0 284.2 0H163.8c-12.1 0-23.2 6.8-28.6 17.7zM416 128H32L53.2 467c1.6 25.3 22.6 45 47.9 45H346.9c25.3 0 46.3-19.7 47.9-45L416 128z"></path>
                                                </svg>
                                            </a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                {% if products|length == 0 %}
                    <h3 class="text-center mt-4">No results! Please try again.</h3>
                {% endif %}
            </div>
        </div>
        <div class="container text-center bg-container">
            <div class="container text-center">
                <div class="row row-cols-1">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/checkout.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Confirmare plată {% endblock %}

{% block content %}
    <div class="container-lg mt-5">
        <div class="row">
            <div class="col-md-12 text-center">
                <h1 class="display-4 mb-4">Confirmare plată</h1>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-6">
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        {{ form.as_p }}
                    </div>
                    <h6>Alegere curier:</h6>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="curier" id="curier1" value="Curier1" checked>
                        <label class="form-check-label" for="curier1">
                            Fan Curier
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="curier" id="curier2" value="Curier2">
                        <label class="form-check-label" for="curier2">
                            DPD
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="curier" id="curier3" value="Curier3">
                        <label class="form-check-label" for="curier2">
                            SameDay
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="curier" id="curier4" value="Curier4">
                        <label class="form-check-label" for="curier2">
                            Posta Romana
                        </label>
                    </div>
                    <br><br>
                    <div class="col-md-3">
                        <a href="{% url 'ms' %}" class="btn btn-outline-success">Confrirma plata</a>
                    </div>
                </form>
            </div>

        </div>
        <div class="row justify-content-center mt-4">
            <div class="col-md-6">
                {% if messages %}
                    <div class="alert alert-info">
                        <ul class="list-unstyled mb-0">
                            {% for message in messages %}
                                <li>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/comenzi_istoric.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}
{% block title %}Comenzile mele{% endblock %}

<div class="container text-center">
        <div class="row ">
            <div class="col-md-10 offset-md-1">
                <div class="row">
                    {% if total_value is 0 %}
                        <h3 class="mb-10 fw-normal text-black">Momentan nu aveti comenzi plasate!</h3>
                        <br><br><br>
                    {% else %}
                        <h3 class="mb-4 fw-normal text-black">Comenzile mele!</h3>
                    {% endif %}
                </div>
            </div>
        </div>
</div>

templates/contact.html
{% extends 'base.html' %}
{% load static %}
<br>
{% block title %}Contact us{% endblock %}

{% block content %}
    <br>
    <div class="container mt-4">
        {% if messages %}
            <div class="alert alert-success">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-6 offset-md-1">
                <form action="{% url 'send-email' %}" method="post" name="feedback" class="form-horizontal">
                    {% csrf_token %}
                    <div class="form-group {% if form.name.errors %}has-error{% endif %}">
                        <label for="id_name" class="control-label">Name</label>
                        <input type="text" name="name" class="form-control"
                               id="id_name"
                               value="{% if request.method == 'POST' %}{{ request.POST.name }}{% endif %}"/>
                        {% if form.name.errors %}
                            <ul class="errorlist">
                                {% for error in form.name.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                        <p class="help-block">Name is a required field</p>
                    </div>
                    <div class="form-group {% if form.email.errors %}has-error{% endif %}">
                        <label for="id_email" class="control-label">E-mail Address</label>
                        <input class="form-control" type="text" name="email"
                               id="id_email"
                               value="{% if request.method == 'POST' %}{{ request.POST.email }}{% endif %}"/>
                        {% if form.email.errors %}
                            <ul class="errorlist">
                                {% for error in form.email.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                        <p class="help-block">A valid e-mail address is required.</p>
                    </div>
                    <div class="form-group {% if form.subject.errors %}has-error{% endif %}">
                        <label for="id_subject" class="control-label">Subject</label>
                        <input type="text" name="subject" class="form-control"
                               id="id_subject"
                               value="{% if request.method == 'POST' %}{{ request.POST.subject }}{% endif %}"/>
                        {% if form.subject.errors %}
                            <ul class="errorlist">
                                {% for error in form.subject.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                        <p class="help-block">Subject should contain at least 3 characters.</p>
                    </div>
                    <div class="form-group {% if form.message.errors %}has-error{% endif %}">
                        <label for="id_message" class="control-label">Message</label>
                        <textarea name="message" class="form-control" id="id_message" rows="4">
                            {% if request.method == 'POST' %}{{ request.POST.message }}{% endif %}
                        </textarea>
                        {% if form.message.errors %}
                            <ul class="errorlist">
                                {% for error in form.message.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                        <p class="help-block">Message should contain at least 10 characters.</p>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <button type="submit" class="btn btn-outline-success">Send</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-4 offset-md-1">
                <h4>Contact Information</h4>
                <ul>
                    <li>Ne puteți găsi la:</li>
                    <li>Email: contact@onlinestore.com</li>
                    <li>Phone: +40 727 227 222</li>
                    <li>Adresa: B-du Dacia, Nr1, Mioveni, Romania</li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

templates/create_user.html
{% extends 'base.html' %}

{% block title %} Create a new account {% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-6 offset-md-3">
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Create a new account</h3>
                    </div>
                    <form method="post">
                        {% csrf_token %}
                        <div class="card-body">
                            <div class="row">
                                {{ form.as_p }}
                            </div>
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-outline-success">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/favorite.html
{% extends 'base.html' %}
{% block content %}
    {% if products %}
        <h2>Your Favorites</h2>
        <hr>
        {% for product in products %}
            <div class="card me-2 mb-2" style="width: 16rem;">
                <img style="object-fit: cover;" class="card-img mt-2" width="268" height="200"
                     src="{{ product.image.url }}">
                <div class="mt-3 text-center">
                    <h5 class="card-title">{{ product.title }}</h5>
                    <p class="text-muted">${{ product.price }}</p>
                    <a href="{{ product.get_absolute_url }}" class="mb-3 btn btn-primary w-100">Buy Now</a>
                </div>
                <a href="{% url 'shop:remove_from_favorites' product.id %}"
                   class="mb-3 btn btn-outline-danger">Remove</a>
            </div>
        {% endfor %}
    {% else %}
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8 mt-5 pt-5 text-center">
                <br>
                <h3 class="text-muted text-capitalize">favorites list is empty..!</h3>
                <a href="/" class="text-primary text-decoration-none">Back</a>
            </div>
            <div class="col-md-2"></div>
        </div>
    {% endif %}
{% endblock %}

templates/product_create.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Create a new product {% endblock %}

{% block content %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Create a new product</h3>
                    </div>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="card-body">
                            {{ form.as_p }}
                        </div>
                        <div class="d-flex justify-content-between">
                            <div class="col-md-2 offset-md-3">
                                <button type="submit" class="btn btn-outline-success">Save</button>
                            </div>
                            <div class="col-md-4 offset-md-1">
                                <button type="submit" class="btn btn-outline-danger">Cancel</button>
                            </div>
                        </div>
                        <br>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <br>
{% endblock %}

templates/succes_payment.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}
{% block title %}Mulțumim{% endblock %}

{% block content %}<br><br><br><br><br><br><br>
    <div class="row">
        <br><br><br><br><br>
        <div class="col-md-6 offset-md-4">
            <h1>Mulțumim pentru comanda!</h1>
            <p>Produsele vor ajunge la tine in cel mai scurt timp posibil!</p><br><br><br><br><br><br><br>
        </div>
        <div class="col-md-6">
        </div>
    </div>
    <script>
        setTimeout(function () {
            window.location.href = "{% url 'home_page' %}";
        }, 1000);
    </script>
{% endblock %}

templates/success_mail_contact.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}
{% block title %}Mulțumim{% endblock %}

{% block content %}<br><br><br><br><br><br><br>
    <div class="row">
        <br><br><br><br><br>
        <div class="col-md-6 offset-md-4">
            <h1>Mulțumim pentru contactare!</h1><br><br>
            <p>Vom incerca sa raspundem solicitari dumneavoastra in cel mai scurt timp posibil!</p>
            <br><br><br><br><br><br><br>
        </div>
        <div class="col-md-6">

        </div>
    </div>
    </div>
    <script>
        setTimeout(function () {
            window.location.href = "{% url 'home_page' %}";
        }, 1000); // Delay for 2 seconds
    </script>
{% endblock %}